#!/usr/bin/env bash
# Restore checkpoints/caches from the soar-eleuther-i6-hierarchy org back into
# their original local folders, using scripts/hf_sync/upload_manifest.tsv as
# the map of repo_id -> local_path (the same manifest upload_to_hub.sh used).
#
# Usage:
#   scripts/hf_sync/download_from_hub.sh                # restore everything in the manifest
#   scripts/hf_sync/download_from_hub.sh <repo-name>...  # restore only these repos (org/ prefix optional)
#
# A "file" row (a lone *.pt checkpoint) gets downloaded into its parent dir,
# since the repo holds just the basename. A "dir" row (an SAE checkpoint
# folder or a token_cache folder) gets downloaded straight into local_path,
# since the repo holds that folder's contents.
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
MANIFEST="$HERE/upload_manifest.tsv"

if [ -z "${HF_TOKEN:-}" ] && [ -f "$ROOT/.env" ]; then
  HF_TOKEN=$(grep -E "^HF_TOKEN_Write=" "$ROOT/.env" | cut -d= -f2-)
  export HF_TOKEN
fi

if [ ! -f "$MANIFEST" ]; then
  echo "No manifest at $MANIFEST -- it's regenerated by generate_manifest.py," >&2
  echo "but that needs the local files to still exist. If you already deleted" >&2
  echo "them, keep this manifest around instead of regenerating it." >&2
  exit 1
fi

# optional filter: only restore repos named on the command line
FILTERS=("$@")
matches_filter() {
  local repo="$1"
  [ ${#FILTERS[@]} -eq 0 ] && return 0
  for f in "${FILTERS[@]}"; do
    [[ "$repo" == "$f" || "$repo" == *"/$f" ]] && return 0
  done
  return 1
}

cd "$ROOT"
total=$(grep -c . "$MANIFEST")
n=0

while IFS=$'\t' read -r local repo rtype kind; do
  [ -z "$local" ] && continue
  n=$((n+1))
  matches_filter "$repo" || continue

  if [ "$kind" = "dir" ]; then
    target="$local"
  else
    target="$(dirname "$local")"
  fi
  mkdir -p "$target"

  echo "=== [$n/$total] $repo ($rtype, $kind) -> $target ==="
  hf download "$repo" --repo-type "$rtype" --local-dir "$target" --exclude ".gitattributes"
done < "$MANIFEST"
