#!/usr/bin/env bash
# Upload every row in scripts/hf_sync/upload_manifest.tsv (generated by
# generate_manifest.py) to the soar-eleuther-i6-hierarchy org on HF Hub.
#
# Usage:
#   python3 scripts/hf_sync/generate_manifest.py   # writes upload_manifest.tsv
#   ${EDITOR:-vi} scripts/hf_sync/upload_manifest.tsv   # review / trim rows
#   scripts/hf_sync/upload_to_hub.sh
#
# Requires: `hf` CLI (huggingface_hub), and a write-scoped token either
# already active (`hf auth login`) or in .env as HF_TOKEN_Write.
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
MANIFEST="$HERE/upload_manifest.tsv"
LOG="$HERE/upload_log.txt"
STATUS="$HERE/upload_status.tsv"

if [ -z "${HF_TOKEN:-}" ] && [ -f "$ROOT/.env" ]; then
  HF_TOKEN=$(grep -E "^HF_TOKEN_Write=" "$ROOT/.env" | cut -d= -f2-)
  export HF_TOKEN
fi
if [ -z "${HF_TOKEN:-}" ]; then
  echo "No HF_TOKEN set and no HF_TOKEN_Write found in .env -- aborting." >&2
  exit 1
fi

if [ ! -f "$MANIFEST" ]; then
  echo "No manifest at $MANIFEST -- run generate_manifest.py first." >&2
  exit 1
fi

cd "$ROOT"
: > "$LOG"
: > "$STATUS"

total=$(grep -c . "$MANIFEST")
n=0

while IFS=$'\t' read -r local repo rtype kind; do
  [ -z "$local" ] && continue
  n=$((n+1))
  echo "=== [$n/$total] $repo ($rtype) <- $local ===" | tee -a "$LOG"
  if hf upload "$repo" "$local" --repo-type "$rtype" --no-private \
      --commit-message "Upload $local from soar-eleuther-i6-hierarchy" >>"$LOG" 2>&1; then
    printf '%s\t%s\t%s\tOK\n' "$repo" "$local" "$rtype" >> "$STATUS"
  else
    printf '%s\t%s\t%s\tFAIL\n' "$repo" "$local" "$rtype" >> "$STATUS"
  fi
done < "$MANIFEST"

echo "DONE" >> "$LOG"
ok=$(grep -c -F $'\tOK' "$STATUS" || true)
fail=$(grep -c -F $'\tFAIL' "$STATUS" || true)
echo "Finished: $ok ok, $fail failed (of $total)" | tee -a "$LOG"
